name: Build

on:
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read
  
jobs:
  cumulocity-cypress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Validate and test bin paths
        run: |
          # Extract bin paths from package.json
          BIN_PATHS=$(jq -r '.bin[]' package.json)

          cd dist/

          # Check if each bin path exists and is executable
          for BIN_PATH in $BIN_PATHS; do
            if [ ! -f "$BIN_PATH" ]; then
              echo "Bin path $BIN_PATH does not exist."
              exit 1
            fi
            if [ ! -x "$BIN_PATH" ]; then
              echo "Bin path $BIN_PATH is not executable."
              exit 1
            fi
          done

          # Test the --version command for each bin path
          for BIN_PATH in $BIN_PATHS; do
            VERSION_OUTPUT=$(node $BIN_PATH --version)
            echo "$BIN_PATH version: $VERSION_OUTPUT"
            if [[ ! "$VERSION_OUTPUT" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "Invalid version output for $BIN_PATH: $VERSION_OUTPUT"
              exit 1
            fi
          done

  pact-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install yalc
        run: npm install -g yalc

      - name: Run yalc publish
        run: npm run yalc:publish

      - name: Build pact runner
        run: |
          cd packages/pact-runner
          npm run package:dev
